version: '3.8'
services:
  3205front:
    build:
      context: ./
      dockerfile: client/Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
  
  3205backend:
    build:
      context: ./
      dockerfile: backend/Dockerfile
    ports:
      - "3001:3001"